### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by auok1** [LoongServe/LoongServe#2]
Where is path "/mnt/petrelfs/zhaoyihao/intlsy/research/datasets/preprocessed"? I need preprocessed datasets but can't find them.Thanks a lot.

**Comment by auok1** [comment]
Where is path "/mnt/petrelfs/zhaoyihao/intlsy/research/datasets/preprocessed"? I need preprocessed datasets but can't find them.Thanks a lot.

**Comment by interestingLSY** [comment]
Sorry, but we are unable to share them since they are too big. We have provided instructions about how to reproduce those datasets [here](https://github.com/LoongServe/LoongServe/blob/main/docs/artifact-eval/supplemental/repro-dataset.md).
